### ISSUE TITLE
composer install fails on cakephp application template 

### ISSUE THREAD

**Issue by quasiperfect** [gourmet/filters#2]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gourmet/filters ^0.1.0 -> satisfiable by gourmet/
filters[v0.1.0].
    - gourmet/filters v0.1.0 requires cakephp/cakephp 3.0.*-dev -> no matching p
ackage found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more det
  ails.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by phillaf** [comment]
This is fixed by 6dfda019
We'll need a version bump to 0.2

**Comment by jadb** [comment]
Fixed, v1.0.0 tagged. Try again now @quasiperfect and thanks for reporting it.
